#!/bin/bash

CURPATH=`pwd`
# domain for containers
CONTAINER_DOMAIN=phoenix.duc.com
CONTAINER_HOSTS=${CURPATH}/docker-container-hosts

# find the dns IP address
findDockerDnsIP() {
    dnsip=`ip addr show dev docker0 | grep 'inet ' | awk -F' ' '{ print $2  }' | awk -F'/' '{ print $1  }'`
    eval "$1=${dnsip}"
}

autoCreateHostsFile() {
    echo "# auto generated by $0" > ${CONTAINER_HOSTS}
    for CID in `sudo docker ps -q`;do
        IP=`sudo docker inspect --format '{{ .NetworkSettings.IPAddress }}' ${CID}`

        NAME=`sudo docker inspect --format '{{ .Config.Hostname }}' ${CID}`
        echo "${IP} ${NAME}.${CONTAINER_DOMAIN}" >> ${CONTAINER_HOSTS}
    done
    sudo pkill -x -HUP dnsmasq
}

autoStartDockerSlaveImage() {
    NUM=$1
    DNSIP=$2
    i=1
    while [ $i -lt $NUM ]
    do
        sudo docker run -itd \
            --privileged \
            --dns ${DNSIP} \
            --name slave$i \
            --hostname slave$i \
            dockerfile/ubuntu14.04:ambari-agent
        i=$(( $i + 1 ))
    done 
}

autoStartDockerMasterImage() {
    DNSIP=$1
    sudo docker run -itd \
        --privileged \
        --dns ${DNSIP} \
        --name master \
        --hostname master \
        dockerfile/ubuntu14.04:ambari-agent
}

autoStartDockerAmbariImage() {
    DNSIP=$1
    sudo docker run -itd \
        --dns ${DNSIP} \
        --name ambari \
        --hostname ambariserver \
        -p 8088:8080 \
        dockerfile/ubuntu14.04:ambari
    sleep 1
}

DNSIP='127.0.0.1'
findDockerDnsIP DNSIP
sudo docker rm -f `sudo docker ps -a -q`
autoStartDockerMasterImage ${DNSIP}
autoStartDockerSlaveImage 6 ${DNSIP}
autoStartDockerAmbariImage ${DNSIP}
autoCreateHostsFile
sudo docker exec -it ambari /bin/bash
